version: '3.9'
services:
  popp-nginx:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./src:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - popp-php-fpm
  popp-php-fpm:
    image: php:8-fpm
    volumes:
      - ./src:/var/www/html
